### ISSUE TITLE
Add MConverter - File Converter & PDF Compressor

### ISSUE THREAD

**Issue by marto55555** [notangelmario/paquet#11]
**App URL:** https://mconverter.eu/
**App author:** MConverter
**App category:** Utilities
**App description:** Convert files in bulk with ease. MConverter supports most media, e-book, office & archive formats, including new ones like AVIF and JPEG XL. Compress PDFs by up to 90% for free with adjustable quality.
**Maskable icon URL:** https://mconverter.eu/img/icon-pwa.png

**What are the platforms you have tested this app on?**
* Windows 8, 10, 11
* macOS
* ChromeOS
* iOS 15
* Android 4.4+

**Comment by notangelmario** [comment]
Hi! I've added your app to Paquet. Check it out here https://paquet.shop/app/ad6d6cd6-5aaf-47a5-9bc3-3d4d9ea9ffe2. BTW I used it to convert all icons on the platform to webp. Really cool app!
