### ISSUE TITLE
App Request: Moody Man Game

### ISSUE THREAD

**Issue by shi2rsingh** [notangelmario/paquet#23]
**App URL:** https://moodyman.gamelette.com/
**App author:** Shishir Singh ( @shi2rsingh )
**App category:** Games
**App description:** Moody Man - A Hangman type game of guess
**Small maskable icon URL:** https://moodyman.gamelette.com/icons/maskable_icon_x128.png
**Large maskable icon URL:** https://moodyman.gamelette.com/icons/maskable_icon_x512.png

**What are the platforms you have tested this app on?**
* Windows
* Linux
* Android
* iOS (iOS doesn't support PWAs, but can run standalone)

**Comment by notangelmario** [comment]
hi, @shi2rsingh ! At the moment I am working on a developer dashboard and will soon send you a private invitation to get access to your developer dashboard where you can manage your own app. I will get back to you soon!

**Comment by shi2rsingh** [comment]
Sure @notangelmario. Looking forward to it
Thanks

**Comment by notangelmario** [comment]
I've added your app to Paquet! Here's the [listing](https://paquet.shop/app/f2599a89-db74-49b1-afc9-57ecd554151f)
