### ISSUE TITLE
Rec Net

### ISSUE THREAD

**Issue by ZakGhost354313** [notangelmario/paquet#29]
**App URL:** [rec.net](rec.net) 
**App author:** Rec Room
**App category:** Social, Games
**App description:** A social app for the game RecRoom
**Small maskable icon URL:** [https://rec.net/favicon.ico](https://rec.net/favicon.ico) 
**Large maskable icon URL:** An URL pointing to a large icon of the app (preferably 512x512)[https://rec.net/favicon.ico](https://rec.net/favicon.ico) 

**What are the platforms you have tested this app on?**
* iOS

**Comment by notangelmario** [comment]
Hi, @ZakGhost354313! Thanks for your submission! Rec Net is available on [Paquet](https://paquet.shop/app/bc13158b-8c18-416b-8fc5-6761653339db) right now!
