### ISSUE TITLE
Add Farmhand to Game category

### ISSUE THREAD

**Issue by jeremyckahn** [notangelmario/paquet#6]
Paquet is cool! Thanks for making it. 🙂

-----------------------------------------

**App URL**: https://www.farmhand.life/
**App author**: Jeremy Kahn

**What are the platforms you have tested this app on?**
* Linux
* Mac OS
* Windows 10
* iOS
* Android

**Comment by notangelmario** [comment]
Farmhand has been added! Thank you very much for choosing to add your game to Paquet! Soon I'll add a dashboard where you can edit your app and see stats about it.
