### ISSUE TITLE
Quranipfs

### ISSUE THREAD

**Issue by adelpro** [notangelmario/paquet#7]
**App URL:** www.quranipfs.com
**App author:** BENYAHIA-DEV
**App category:** (Utilities)

**Small maskable icon URL:** https://www.quranipfs.com/images/128x128.png
**Large maskable icon URL:** https://www.quranipfs.com/images/512x512.png

**What are the platforms you have tested this app on?**
* Windows 11
* iOS
* Android

**Comment by notangelmario** [comment]
Hi! Thanks for choosing to add your app to Paquet! Could you please provide me a description in english?

**Comment by adelpro** [comment]
** Description **
موقع قرآن - QuranIPFS:
The website allows you to listen to the Holy Quran without the need to download any files, using the Interplanatery File System system IPFS, which is a new and promising technology for file exchange and it's better than torrent.

**Comment by notangelmario** [comment]
Very cool project! You app is now on the shop!
