### ISSUE TITLE
Bad Category: "Utilies"

### ISSUE THREAD

**Issue by rtsfred3** [notangelmario/paquet#78]
**Describe the bug**
There is an extra, bad category called "Utilies" that exists. So far, only "GitHub Status" is impacted by this.

**To Reproduce**

1. Go to [Utilies Category](https://paquet.shop/category/utilies) or [GitHub Status](https://paquet.shop/app/da980043-6054-4935-b25a-04be1db3ebc9) to see this error.

**Expected behavior**
All impacted entries should have "Utilies" changed to "Utilities"

**Comment by notangelmario** [comment]
Thank you for pointing it out. There is a problem with the dependencies that prevents apps from updating properly.

I will also check the 'update' script.

**Comment by notangelmario** [comment]
@all-contributors please add @rtsfred3 for bug reporting
