### ISSUE TITLE
App Request: bundlejs

### ISSUE THREAD

**Issue by okikio** [notangelmario/paquet#79]
**App URL:** https://bundlejs.com
**App Manifest URL:** https://bundlejs.com/manifest.json
**App public repo(GitHub/GitLab if applicable):** https://github.com/okikio/bundlejs
**App author:** @okikio
**Features:** (desktop optimized, requires auth, open source, offline compatible, mobile optimized)

- Desktop optimized
- Mobile optimized
- Open source
- Offline compatible

**Comment by notangelmario** [comment]
Hello again, @okikio! Pretty cool app not going to lie. [Here](https://paquet.shop/app/cdf075ca-1db8-497b-a905-ec557f230bfa) is your app

**Comment by okikio** [comment]
Hey thanks 👍
