### ISSUE TITLE
Check-hadith

### ISSUE THREAD

**Issue by adelpro** [notangelmario/paquet#8]
**App URL:** adelpro.github.io/check-hadith
**App author:** BENYAHIA-DEV
**App category:** ( Utilities)
(Optional)
**Small maskable icon URL:** https://adelpro.github.io/check-hadith/images/128x128.png
**Large maskable icon URL:** https://adelpro.github.io/check-hadith/images/512x512.png
**Description**
Search for hadith nabawi by words or phrases, using Dorar API
**What are the platforms you have tested this app on?**
* Windows 11
* iOS
* Android

**Comment by notangelmario** [comment]
I'm sorry for asking again but I also need an english description. App description is now required when submitting an app request.

**Comment by notangelmario** [comment]
Here is the app you requested: https://paquet.shop/app/61761587-a058-49bc-af11-b15e6392ed75. Hope you like it!
