### ISSUE TITLE
App Request: inthistweet.app

### ISSUE THREAD

**Issue by okikio** [notangelmario/paquet#80]
**App URL:** https://inthistweet.app
**App Manifest URL:** https://inthistweet.app/manifest.json
**App public repo(GitHub/GitLab if applicable):** https://github.com/okikio/inthistweet
**App author:** @okikio
**Features:** (desktop optimized, requires auth, open source, offline compatible, mobile optimized)

- Desktop optimized
- Mobile optimized
- Open source
- Offline compatible

**Comment by notangelmario** [comment]
Hi, @okikio! Thanks for choosing to add your app to Paquet! Your app is available [here](https://paquet.shop/app/38f2b999-e66e-4908-a58a-9e8a52f12409)
