### ISSUE TITLE
Issues when clicking "Back" & "Add to library" buttons in production

### ISSUE THREAD

**Issue by rtsfred3** [notangelmario/paquet#87]
**Describe the bug**
When attempting to click the back button, or the "add to library" button, non action is performed.

**To Reproduce**

1. Go to the [homepage](https://paquet.shop/)
2. Click on the "News" category & select any page for an app
3. Attempt to click the back button in top left corner, attempt to add the app to library
4. See errors

**Expected behavior**
When pressing back button, it takes user to previous page. When adding app to library, it gets added to their library

**Comment by notangelmario** [comment]
This is very interesting. For some reason, production for me doesn't error to me, but the javascript doesn't get loaded. When running the same code in locally, it doesn't error.

This seemes more like a Fresh or Deno Deploy problem.

**Comment by notangelmario** [comment]
Uhm I don't even know what happened. I might be forced to move away from Deno Deploy. After a redeployment everything works. At least that's what I hope. I am going to keep this issue open while I investigate what happened.

**Comment by notangelmario** [comment]
@rtsfred3 please let me know if you find anything. This seems to be an issue with Deno Deploy. I encountered this in the past. I can't let this happen again, and I will be forced to move away from the Deno ecosystem. I will file issues and see if I find anything.

**Comment by lino-levan** [comment]
> After a redeployment everything works.

This makes me think that this is a deno deploy or a caching issue. Could you share some more details (screenshots, etc) about what is going wrong?

**Comment by notangelmario** [comment]
Hi, @lino-levan! I would love to, but I don't have anything relevant to share. The issue is resolved after redeploying. Even without making code changes. 

I use Cloudflare, the proxy has nothing to do with the bug. When I go back to a previous deployment the bug is not there. The same issue affects any device.

**Comment by notangelmario** [comment]
Update: Bug has been resolved, for now.

I will keep this issue open for the next 2 versions.

**Comment by notangelmario** [comment]
This bug seems mostly to have been fixed. I will keep this issue open for a week and see if it occurs again.
