### ISSUE TITLE
Add SimilarWorlds.com to Social category

### ISSUE THREAD

**Issue by nunoperalta** [notangelmario/paquet#9]
**App URL:** https://similarworlds.com
**App author:** Similar Worlds
**App category:** Social
**App description:** Discuss Experiences, Share Stories, Ask Questions, Find Answers, Explore Interests, Make Friends ... Express your true Self!
**Maskable icon URL:** https://images.similarworlds.com/Similar-Worlds-Logo-Symbol-1024-Mask.png

**What are the platforms you have tested this app on?**
* Windows
* Linux
* Android
* iOS (iOS doesn't support PWAs, but can run standalone)

**Comment by notangelmario** [comment]
Thanks for your submission! Your app is available at https://paquet.shop/app/cce2f17e-7132-48be-95f4-6a00d1106ce7

**Comment by nunoperalta** [comment]
Thanks @notangelmario 

Just a note - when I open that link, the "Back" button on the top-left corner doesn't seem to work.
You might want to make it fallback to the homepage :)

Cheers - good work so far!

**Comment by notangelmario** [comment]
still figuring out how to achieve that without breaking history api
