### ISSUE TITLE
Adding Quranipfs

### ISSUE THREAD

**Issue by adelpro** [notangelmario/paquet#96]
As i received an issue on my github repository of QuranIPFS.
Im asking if you can add my app to your Paquet.shop?
Web application link [Quranipfs.com](www.quranipfs.com)
GitHub Repository [GitHub](https://github.com/adelpro/Quranipfs)

**Comment by notangelmario** [comment]
Hi @adelpro! Your app is already on Paquet. I am closing this issue.
